// Generated by scripts/project-schema-walker.mjs from
// extensions/java-core/schema/java-project.schema.json: do not edit by hand.
// The key table project-config.ts validates against (RFC 0006 §6.1).

export const PROJECT_KEYS = {
  "jdk.requirement": {
    "type": "string",
    "pattern": "^[0-9]+$",
    "description": "The Java major version the project needs, e.g. \"21\"; overrides what pom.xml or build.gradle ask for. Absent: the build tool decides."
  },
  "maven.configuration": {
    "type": "string",
    "description": "The Maven configuration to use: a name from maven.configurations here, from batlehub.java.maven.configurations, or a detected ~/.m2/settings*.xml."
  },
  "maven.configurations": {
    "type": "array",
    "items": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": "string",
        "settingsFile": "string",
        "toolchainsFile": "string",
        "mavenHome": "string",
        "profiles": "string[]"
      }
    },
    "description": "Named Maven configurations, the same shape as batlehub.java.maven.configurations. A committed settingsFile is announced before it is used."
  },
  "maven.activeProfiles": {
    "type": "array",
    "items": {
      "type": "string"
    },
    "description": "Maven profiles: -P on every goal and the m2e preference."
  },
  "gradle.activeProfiles": {
    "type": "array",
    "items": {
      "type": "string"
    },
    "description": "Reserved: Gradle has no profiles; kept so the file has one shape per tool."
  },
  "registry.enabled": {
    "enum": [
      "ask",
      "true",
      "false"
    ],
    "description": "Whether Maven and Gradle resolve through BatleHub: ask, true, or false (a public repository can say never)."
  }
} as const;

export const PROJECT_SECTIONS = ["jdk","maven","gradle","registry","satellites"] as const;
