import { defineConfig } from "vitepress";
import { withMermaid } from "vitepress-plugin-mermaid";

export default withMermaid(
  defineConfig({
    title: "batlehub-vsx",
    description:
      "The BatleHub VS Code extensions: sign in, keep the credential fresh, browse and install where the editor's gallery cannot be repointed.",
    lang: "en-US",
    lastUpdated: true,
    cleanUrls: true,
    // The RFC template is a form with <placeholders> Vue would parse; it is copied by task rfc:new, not published.
    srcExclude: ["internal/**"],
    themeConfig: {
      nav: [
        { text: "Guide", link: "/guide/install" },
        { text: "Contributing", link: "/contributing/testing" },
        {
          text: "BatleHub",
          link: "https://batleforc.git.batleforc.fr/batlehub",
        },
      ],
      sidebar: [
        {
          text: "Guide",
          items: [
            { text: "Install", link: "/guide/install" },
            { text: "Broker mode", link: "/guide/broker" },
            { text: "Marketplace mode", link: "/guide/marketplace" },
            { text: "Settings and commands", link: "/guide/settings" },
            { text: "The BatleHub theme", link: "/guide/theme" },
          ],
        },
        {
          text: "Java",
          items: [
            { text: "Overview", link: "/guide/java/" },
            { text: "JDKs", link: "/guide/java/jdk" },
            { text: "The container's resources", link: "/guide/java/resources" },
            { text: "Maven, Gradle, the registry link", link: "/guide/java/build" },
            { text: "Run, menus, the panel", link: "/guide/java/run" },
            { text: "Settings and commands", link: "/guide/java/settings" },
            { text: "Clean removal", link: "/guide/java/removal" },
            { text: "Completion, and the chain", link: "/guide/java/editing" },
            { text: "Groovy, Gradle DSL, Jenkinsfile", link: "/guide/java/groovy" },
          ],
        },
        {
          text: "Contributing",
          items: [
            { text: "Layout and tasks", link: "/contributing/layout" },
            { text: "Testing", link: "/contributing/testing" },
            { text: "Releasing", link: "/contributing/releasing" },
            { text: "Team diaries", link: "/diary/" },
          ],
        },
        // BEGIN rfc-sidebar — generated by `task rfc:index` from each RFC's header table — do not edit by hand
        {
          text: "In the works",
          items: [
            {
              text: "0002 — Headless engine",
              link: "/rfc/0002-headless-engine-mcp",
            },
            {
              text: "0003 — Orchestrated runs",
              link: "/rfc/0003-server-run-step-kinds",
            },
            {
              text: "0004 — Run-config sources",
              link: "/rfc/0004-run-config-sources",
            },
            {
              text: "0005 — Inspection profiles",
              link: "/rfc/0005-shared-inspection-profiles",
            },
            {
              text: "0006 — Project config",
              link: "/rfc/0006-shared-project-config",
            },
            {
              text: "0007 — IntelliJ import",
              link: "/rfc/0007-intellij-import-full",
            },
            {
              text: "0008 — Kotlin",
              link: "/rfc/0008-kotlin-satellite",
            },
            {
              text: "0009 — Scala",
              link: "/rfc/0009-scala-satellite",
            },
            {
              text: "0010 — Spring Boot",
              link: "/rfc/0010-spring-boot-satellite",
            },
            {
              text: "0011 — Quarkus",
              link: "/rfc/0011-quarkus-satellite",
            },
            {
              text: "0012 — Chain completion",
              link: "/rfc/0012-chain-completion",
            },
            {
              text: "0013 — Spell checking",
              link: "/rfc/0013-spell-checking",
            },
            {
              text: "0015 — Generate shortcuts",
              link: "/rfc/0015-generate-shortcuts",
            },
            {
              text: "0016 — Inspections growth",
              link: "/rfc/0016-inspections-growth",
            },
          ],
        },
        {
          text: "Parked",
          items: [
            {
              text: "0017 — Server kinds",
              link: "/rfc/0017-server-kinds",
            },
            {
              text: "0018 — Rust syntactic tier",
              link: "/rfc/0018-rust-syntactic-tier",
            },
          ],
        },
        {
          text: "Settled",
          items: [
            {
              text: "0001 — Java extensions",
              link: "/rfc/0001-java-env",
            },
            {
              text: "0014 — BatleHub theme",
              link: "/rfc/0014-batlehub-theme",
            },
          ],
        },
        // END rfc-sidebar
      ],
      socialLinks: [
        { icon: "github", link: "https://github.com/batleforc/batlehub-vsx" },
      ],
      search: { provider: "local" },
      outline: [2, 3],
    },
  }),
);
