import { defineConfig } from "vitepress";
import { withMermaid } from "vitepress-plugin-mermaid";

export default withMermaid(
  defineConfig({
    title: "batlehub-vsx",
    description:
      "The BatleHub VS Code extensions: sign in, keep the credential fresh, browse and install where the editor's gallery cannot be repointed.",
    lang: "en-US",
    lastUpdated: true,
    cleanUrls: true,
    // The RFC template is a form with <placeholders> Vue would parse; it is copied by task rfc:new, not published.
    srcExclude: ["internal/**"],
    themeConfig: {
      nav: [
        { text: "Guide", link: "/guide/install" },
        { text: "Contributing", link: "/contributing/testing" },
        {
          text: "BatleHub",
          link: "https://batleforc.git.batleforc.fr/batlehub",
        },
      ],
      sidebar: [
        {
          text: "Guide",
          items: [
            { text: "Install", link: "/guide/install" },
            { text: "Broker mode", link: "/guide/broker" },
            { text: "Marketplace mode", link: "/guide/marketplace" },
            { text: "Settings and commands", link: "/guide/settings" },
          ],
        },
        {
          text: "Java",
          items: [
            { text: "Overview", link: "/guide/java/" },
            { text: "JDKs", link: "/guide/java/jdk" },
            { text: "The container's resources", link: "/guide/java/resources" },
            { text: "Maven, Gradle, the registry link", link: "/guide/java/build" },
            { text: "Run, menus, the panel", link: "/guide/java/run" },
            { text: "Settings and commands", link: "/guide/java/settings" },
            { text: "Clean removal", link: "/guide/java/removal" },
            { text: "Groovy, Gradle DSL, Jenkinsfile", link: "/guide/java/groovy" },
          ],
        },
        {
          text: "Contributing",
          items: [
            { text: "Layout and tasks", link: "/contributing/layout" },
            { text: "Testing", link: "/contributing/testing" },
            { text: "Releasing", link: "/contributing/releasing" },
          ],
        },
        // BEGIN rfc-sidebar — generated by `task rfc:index` from each RFC's header table — do not edit by hand
        {
          text: "In the works",
          items: [
            {
              text: "0001 — Java extensions",
              link: "/rfc/0001-java-env",
            },
          ],
        },
        // END rfc-sidebar
      ],
      socialLinks: [
        { icon: "github", link: "https://github.com/batleforc/batlehub-vsx" },
      ],
      search: { provider: "local" },
      outline: [2, 3],
    },
  }),
);
