#!/usr/bin/env node
// `THIRD-PARTY.md` per extension (RFC 0001 decision 22): every dependency
// esbuild bundled into dist/, with its licence, read from the metafile the
// bundle step can write and from node_modules' package.json files. The
// extensions ship no runtime `dependencies`; what is bundled is what the
// metafile lists.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

for (const ext of ["java-core", "java-groovy", "batlehub-vsx", "che-notify", "che-remote-ssh", "che-clipboard"]) {
  const root = `extensions/${ext}`;
  if (!existsSync(`${root}/esbuild.mjs`)) continue;
  execFileSync("node", ["esbuild.mjs"], { cwd: root, env: { ...process.env, ESBUILD_METAFILE: "1" }, stdio: "ignore" });
  const metaPath = `${root}/dist/meta.json`;
  if (!existsSync(metaPath)) {
    console.log(`${ext}: no metafile (esbuild.mjs does not honour ESBUILD_METAFILE); skipped`);
    continue;
  }
  const meta = JSON.parse(readFileSync(metaPath, "utf8"));
  const pkgs = new Map();
  for (const input of Object.keys(meta.inputs)) {
    // pnpm nests `node_modules/.pnpm/<pkg>@<v>/node_modules/<pkg>/…`: the last segment is the package.
    const all = [...input.matchAll(/node_modules\/((?:@[^/]+\/)?[^/]+)/g)].filter((x) => x[1] !== ".pnpm");
    const m = all.at(-1);
    if (!m) continue;
    const name = m[1];
    if (pkgs.has(name)) continue;
    const dir = input.slice(0, m.index + m[0].length);
    try {
      const p = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
      pkgs.set(name, { version: p.version, license: p.license ?? "(unknown)" });
    } catch {
      pkgs.set(name, { version: "?", license: "(unknown)" });
    }
  }
  const rows = [...pkgs.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([n, p]) => `| ${n} | ${p.version} | ${p.license} |`);
  const jdt = existsSync(`${root}/jdt`) ? "\n\nThe JDT bundle under `jdt/` is built from Eclipse JDT (EPL-2.0) and JDT.LS (EPL-2.0); their notices ship inside the jar." : "";
  writeFileSync(`${root}/THIRD-PARTY.md`, `# Third-party notices — ${ext}\n\nGenerated by \`task ext:licenses\`: what esbuild bundled into \`dist/\`.\n\n| Package | Version | License |\n| --- | --- | --- |\n${rows.join("\n") || "| (nothing bundled) | | |"}${jdt}\n`);
  console.log(`${ext}: ${pkgs.size} bundled package(s)`);
}
